### ISSUE TITLE
大概看了下ec-do-2.0.0.js的代码，有点建议

### ISSUE THREAD

**Issue by BruceKellan** [chenhuiYj/ec-do#13]
1. 可以将不同功用的归类，比如用于字符串的就是StringUtils，用于DOM的就是DOMUtils这样子，更清晰
2. 我觉得不应该将函数中的Type用数字作区分，比如changeCase函数，用1表示首字母大写，用2表示首字母小写，这样子代码的可读性会很差，建议使用字符串类型，或者抽出来成为constant

**Comment by chenhuiYj** [comment]
感谢你的建议。
1.在方法里面不加String，DOM等关键字，就是因为加了之后，方法名会长，到时候写的效率会受到影响。
2.Type这个用数字是因为不知道该如何把这个意思表达出来。所以就用了字符串。

这两个问题，也是我考虑的范围之内。非常值得商榷

**Comment by IEasying** [comment]
@chenhuiYj

**Comment by hamsterBiscuit** [comment]
有一点小看法想跟作者交流一下，求数组最大值可以使用Math.max(...arr)，舍弃apply

**Comment by chenhuiYj** [comment]
这个可以试下

**Comment by chenhuiYj** [comment]
感谢建议，看到好像不止这个api，很多地方都可以使用...
