### ISSUE TITLE
关于randomWord函数我有个不太明白的地方?

### ISSUE THREAD

**Issue by wangdabaoqq** [chenhuiYj/ec-do#15]
我觉得这个函数有个疑问, 我开始以为调用`randomWord()`函数时传递的数字, 是可以得到我传递时对应的字符长度. 所以我这里有点疑问, 我试了下, 发现得到的不是我传递的数字长度. 那么传递的数字的作用是什么?
麻烦您解答下.
打扰了.

**Comment by chenhuiYj** [comment]
那个是一个进制数，比如传2，就是返回一个二进制的随机码。传10，就是10进制。传16就是十六进制。传值范围是2-36.

**Comment by wangdabaoqq** [comment]
我觉得这个函数如果超出了2或36之间就会报错吧。这样是不是有点不太合适。说的不对别见怪。




| |
王凯
邮箱：wangdabao221@163.com
|

签名由 网易邮箱大师 定制

在2018年06月21日 12:48，chenhuiYj 写道：

Closed #15.

**Comment by chenhuiYj** [comment]
会啊，整个是限制，就像toString函数也只能输出2-36一样
