### ISSUE TITLE
增加 补零和字符串转DOM？！ 

### ISSUE THREAD

**Issue by zss1004504439** [chenhuiYj/ec-do#18]
` function PrefixInteger(num, length = 2) {
        return (Array(length).join("0") + num).slice(-length);
  }
`
`
    function strToNode(str = "<div class='strToNode'></div>") {
      let tempNode = document.createElement('div');
      tempNode.innerHTML = str;
      return tempNode.firstElementChild;
    }
`

**Comment by chenhuiYj** [comment]
首先感谢提议，但是如果把补零和转 DOM 放一起操作，不会很灵活。因为补零后怎么操作无法得知
