### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by buptxu** [chenhuiYj/ec-do#3]
1. 数组求和那个函数用reduce方法不好吗？
2. 随机码那个函数加上随机码长度更实用吧？
3.得到n1-n2下标的数组，用slice方法好点吧？

**Comment by chenhuiYj** [comment]
感谢您的宝贵建议
1.数组求和之前没有使用，是因为没怎么了解这个方法，现在使用了reduce，代码量少了些。
2.随机码那个加上长度我之前也有考虑过，但是后来没有加上。是因为比如ecdo.randomNumber(36),返回的是一个10来位的字符串，万一我想要20来位，30来位的字符串呢，这个暂时没想怎么弄！
ps:ecdo.randomNumber这个函数名也改了，因为重名了！改成了另一个函数名！
3.之前没用slice方法，是因为担心函数传参的时候，没有传h2，那么h2就是underfind，如果是underfind。但是报错，但是昨晚试了一下，貌似没有报错，就使用这个了！
