### ISSUE TITLE
有一处方法使用方式不懂

### ISSUE THREAD

**Issue by forget1** [chenhuiYj/ec-do#4]
对于其中的html方法，具体的调用方式是什么样子的呢？
是`html(documrnt.getElementById('demo'),'123')`这种还是`html(documrnt.getElementById('demo'))`这样的呢？

**Comment by chenhuiYj** [comment]
和jquery写法一样的。ecDo.html(documrnt.getElementById('demo'))，这样写就是获取这个元素的innerHTML。ecDo.html(documrnt.getElementById('demo')，‘hello world’)，这样写就是设置这个元素的innerHTML为‘hello world’。
