### ISSUE TITLE
ajax 错误

### ISSUE THREAD

**Issue by ywzhaiqi** [chenhuiYj/ec-do#5]
https://github.com/chenhuiYj/ec-do/blob/9e079f30ac8fd50a2372e24b9f72749d86eea205/ec-do.js#L610-L613

这里错了吧，2个 obj.success

**Comment by ywzhaiqi** [comment]
这 ajax 好坑，用了 `type: 'PUT'`，我说怎么没反应，原来是不支持。。。

**Comment by chenhuiYj** [comment]
感谢你的提醒，我自己的过失，当时整理的时候，没处理好，我晚些就整理下再提交
1.第一个写错了，应该是obj.error= obj.error || function () { 
             }; 
2.这里我暂时只支持get和post提交，其它方式提交我没在实际项目上用过，就不处理
