### ISSUE TITLE
原生方案

### ISSUE THREAD

**Issue by Cologler** [chenhuiYj/ec-do#7]
*基于 https://segmentfault.com/a/1190000010225928 这篇文章（比较好辨识……）*

库中部分 api 有原生方案的选择：

## `trim(str, type)` case 2, 3, 4

* `String.prototype.trim`
* `String.prototype.trimLeft`
* `String.prototype.trimRight`

## `repeatStr(str, count)`

`String.prototype.repeat`

## `sumArr(arr)`

`[1, 2, 3, 4].reduce((x, sum) => x + sum, 0)`

## `getEleCount (obj, ele)`

要用 `===` ？

## `hasClass(obj, classStr)`

`obj.classList.contains`

## `addClass(obj,classStr)`

`obj.classList.add`

## `removeClass(obj, classStr)`

`obj.classList.remove`

## `replaceClass(obj,classStr)`

`obj.classList.replace`

## `siblings(obj)`

`Array.from(obj.parentNode.children).filter(z => z !== obj)`

## `css(obj, json)`

`Object.assign(obj, json)`

## `getUrlPrmt(url)` & `setUrlPrmt(obj)`

``` js
const url = new URL('https://github.com/chenhuiYj/ec-do/issues/new?a=1');
url.searchParams.get('a') // get
url.searchParams.set('b', '44') // set
urlX.href // https://github.com/chenhuiYj/ec-do/issues/new?a=1&f=1
```

# 尾声

替换 prototype 时不少库（如 jQuery）的做法是这样，不会造成覆盖原生方法：

``` js
String.prototype.trim = String.prototype.trim || function(type) { ... }
```

还有些其它问题不属于【原生方案】这一项，就不写在这了。

**Comment by chenhuiYj** [comment]
1.我在文章差不多末尾的部分说过，不建议String.prototype.trim这种写法，污染了原生对象，造成不必要开销，也有可会覆盖原来的方法。据我所知，jquery没有替换原生对象的prototype，所涉及的，是jquery对象的prototype。并不是原生对象的prototype。
2.getEleCount这个方法，是我不严谨，应该使用===，而不是==。
3.css(obj, json)这个没看明白您的意思，我的css方法，相当于jquery的css方法，是设置属性的。不是合并对象的！
4.看到您有些建议，确实很好，也非常感激，在以后的版本迭代里面我会逐渐的改！

**Comment by Cologler** [comment]
@chenhuiYj 我说的尾声就是不可能覆盖原来的方法的啊

**Comment by chenhuiYj** [comment]
我明白你的意思，但是万一有哪个api没记住，你命名的刚好和那个api同名，到时候如果你要用那个aip的时候。就可能会有问题。即使确保不覆盖原来的方法，也不建议这样做！原因就是我说的那样！

**Comment by Cologler** [comment]
@chenhuiYj 关于 css 的那个是我写漏了，应该是这个：`Object.assign(obj.style, json);`

**Comment by chenhuiYj** [comment]
这个写法，您的意思就是想css这个方法不会覆盖之前的样式，起到一个追加样式的功能吗？现在这个方法是给一个对象设置样式，是会覆盖原来的样式的，不会追加样式。不过你的这个追加样式的想法挺好，也得考虑是不是应该改下！

**Comment by Cologler** [comment]
@chenhuiYj 理解你的意思了。你是指这种情况吧：

``` js
function A() { ... }
?.prototype.B = ?.prototype.B || A;
```

然后你想调用 `A` 的时候却调用到原生的 `B`。

虽然我认为的是如果两个名字一样的函数行为不一样反而很奇怪。

**Comment by Cologler** [comment]
@chenhuiYj 

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

`Object.assign(obj.style, json)` 是 `json` 中所有的覆盖到前者上，并不是追加。

**Comment by chenhuiYj** [comment]
不是，String.prototype.trim = String.prototype.trim || function(type) { ... }  这种写法和你上面的写法是两回事了！这样可以确保不会覆盖原来的方法，就是不建议！
Object.assign(obj.style, json)，我说的追加，如果json里面包含对象原来没有的样式就是追加到对象里面了，有就覆盖！

**Comment by Cologler** [comment]
@chenhuiYj 关于 `prototype.trim` 那个没理解你在说什么。我命名 `A()` 单纯只是为了「然后你想调用 A 的时候却调用到原生的 B。」这一行好说明而已……

关于 `css`，但是你当前的代码就是：

``` js
    //设置样式
    css: function (obj, json) {
        for (var attr in json) {
            obj.style[attr] = json[attr];
        }
    },
```

行为和 `Object.assign(obj.style, json)` 是一样的。如果你觉得不一样，你可以举个例子。

**Comment by chenhuiYj** [comment]
1.我的意思是`String.prototype.trim = String.prototype.trim || function(type) { ... }`这种写法不会出现
`function A() { ... }?.prototype.B = ?.prototype.B || A;`这个情况。
而且，这样写，也不会出现：想调用 A 的时候却调用到原生的 B。因为A就是A，和原生的 B没什么关系！因为原生的B方法，如果存在就调用原生的B方法，不存在就把A方法赋值给原生的B方法。但是也不会影响到A；
2.你的意思是：比如一个对象，他本身样式是{diapaly:block;color:red;}，现在赋值{diapaly:inline;font-size:16px;}。最后得出的结果是{diapaly:inline;font-size:16px;color:red;}对吧！我现在的做法是得出的结果是{diapaly:inline;font-size:16px;}

**Comment by Cologler** [comment]
……你仔细看一遍你的代码，你现在的做法是得出的结果 **并不是** `{diapaly:inline; font-size:16px;}`

**Comment by Cologler** [comment]
关于 `prototype` 那一点，你估计没理解我在说什么……

这样改下你就好理解了。

``` js
(function () {
function A() { ... }
?.prototype.B = ?.prototype.B || A;
})();
```

这种情况下你想通过 `this.B` 调用 `A` 却调用了 `B`。

我之所以前面给 A 命名并非是代码里面通过 `A()` 调用它，而是在 github 的回复里面用它。
毕竟是说「那个函数」或「前者函数」你是不会清楚我指的哪个函数的。╮（╯＿╰）╭

**Comment by chenhuiYj** [comment]
1.关于prototype，你的意思大概理解。但就是这样写不建议
2.我试了一下。的确是有你说的那个问题，结果如下，我考虑要不要修改
\<div id="div1" style="diapaly:block;color:red;"></div>
ecDo.css(document.getElementById('div1'),{'diapaly':'inline','font-size':'16px'})
\<div id="div1" style="color: red; font-size: 16px; display: inline;"></div>

**Comment by seayao** [comment]
获取兄弟节点siblings这个方法好像有点问题：
当存在筛选条件参数opt时，.和#的过滤原文是:return item.className === opt;
但我觉得应该是:return '.' + item.className === opt;
'#'同上，望参考。

**Comment by chenhuiYj** [comment]
感谢提醒，确实是有问题，我已经修改上传了

**Comment by Cologler** [comment]
@chenhuiYj 这个也有原生方法：`node.matches(selector)`:

``` js
        if(opt){
            var _opt=opt.substr(1);
            var b=[];//定义一个数组，用于储存过滤a的数组
            if(opt[0]==='.'){
                b=a.filter(function(item){return item.className===_opt});
            }
            else if(opt[0]==='#'){
                b=a.filter(function(item){return item.id===_opt});
            }
            else{
                b=a.filter(function(item){return item.tagName.toLowerCase()===opt});
            }
            return b;
        }
```

替换成 `if(opt){ b = a.filter(z => z.matches(opt)); }`
