### ISSUE TITLE
一些建议和BUG，共同完善

### ISSUE THREAD

**Issue by seayao** [chenhuiYj/ec-do#8]
一、字符串相关：
1.关键字加标签findKey()方法:
调用:`findKey('上海自来水来自海上','上海 海','p')`
输出:`<p>上海</p>自来水来自<p>海</p>上`
问题:上海中也包含海，所以我可能期待的结果是:`<p>上<p>海</p></p>自来水来自<p>海</p>上`，当然每个人有不同的想法，我觉得你之前这个也不错，建议而已。
2.过滤字符串filterStr()方法:
原文:`for(var i=0,len=_spstr.length;i<len;i++){
                        if(regText.indexOf(_spstr[i])===-1){
                            _regText+=_spstr[i];
                        }
                        else{
                            _regText+='\\'+_spstr[i];
                        }
                    }`
问题:此for循环中的i与原文中上面的i可能冲突，导致结果出错。
建议:把此for循环中的i改为j，len改为length，期待改进。

二、数组相关：
1.数组扁平化steamroller()方法: 
原文:` if (Array.isArray(arr[i])) {
                newArr.push.apply(newArr, steamroller(arr[i]));
            } else {`    
问题:少一个this，另一种写法同理，期待改进。

三、数据类型相关：
1.数据类型判断istype()方法:
原文:`if(_type){
            var _type = type.toLowerCase();
        }`
问题:if判断语句中的_type应为type，期待改进。

四、ajax相关：
1.ajax()方法:
原文:`if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
                obj.success(xmlHttp.responseText);
            } else {
                obj.error(xmlHttp.responseText);
            }`
问题:当readyState的状态为2和3的时候也会触发请求，故error事件并不能捕捉到异常，期待改进。

五、图片加载相关：
1.图片加载失败aftLoadImg()方法:
原文:`aftLoadImg: function (obj, url, cb) {
        var oImg = new Image(), _this = this;
        oImg.src = url;
       ....
    },`
问题:当图片加载失败时，可能会造成闪烁（一直请求加载，之前遇到过类似问题）
建议:`aftLoadImg: function (obj, url, cb) {
        var oImg = new Image(), _this = this;
        oImg.onerror = "";
        oImg.src = url;
        oImg.onerror = null;
        ....
    },`
2.图片懒加载loadImg()方法:
问题:只能加载前三张图片，期待改进。

六、DOM操作相关：
1.显示与隐藏show()方法:
原文:`obj.style.display = "";`
问题:如果这个DOM对象本身的display属性为none的话，就不起效，但是又不能把他简单的设置为`obj.style.display = "block";`因为要保持它原本的display属性，期待改进。
2.设置文本内容html()方法:
建议:此方法名由"设置文本内容"改为"设置HTML内容的值"，再新增一个“设置元素内容的文本”text()方法。ps：innerHTML是所有浏览器都支持的，innerText是IE浏览器和chrome浏览器支持的，Firefox浏览器不支持，其实innerHTML是W3C组织规定的属性，而innerText属性是IE浏览器自己的属性,不过后来的浏览器部分实现这个属性罢了。

感谢你的贡献，我自己也在你本来的代码里加了一些处理时间相关的方法，感觉时间处理比较常见，当然还有别的，期待你的更新。

本人水平有限，以上建议和意见可能不成熟，望见谅。

**Comment by chenhuiYj** [comment]
不好意思，之前因为工作忙，没有时间看github。
首先，谢谢您提的建议，您的建议很好，在我新提交的代码里面，我也修改了很多！
然后，ajax那个方法，当readyState的状态为2和3的时候，就会执行obj.error(xmlHttp.responseText);。为什么捕捉不到？
最后如果您在代码那里添加了什么，可以提交上来，我看着合并，大家一起维护！

**Comment by seayao** [comment]
关于ajax那个我表述错了：
原文:
<pre>xmlHttp.onreadystatechange = function () {
            if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
                obj.success(xmlHttp.responseText);
            } else {
                obj.error(xmlHttp.responseText);
            }
        };
</pre>
问题:经测试**请求成功的情况下**，err信息会打印两次而且优先于succ的输出，err的第一次打印是空数据（应该是readyState为2的情况），err的第二次打印是正常请求的数据（应该是readyState为2的情况），接下来是succ的正常输出；**请求出错的情况下**，err会打印三次，第一次为空，后两次是err信息。
我的改写:
<pre>xmlHttp.onreadystatechange = function () {
            if (xmlHttp.readyState == 4) {
                //此处可添加一个complete()方法
                if (xmlHttp.status >= 200 && xmlHttp.status < 300 || xmlHttp.status == 304) {
                    obj.success(JSON.parse(xmlHttp.responseText));
                } else {
                    //建议将xmlHttp对象返回，有时候需要根据状态码来进行错误处理
                    obj.error(xmlHttp);
                }
            } else {
                //进行处理也可以忽略
            }
        };
</pre>
关键在于` if (xmlHttp.readyState == 4)`的判断问题，会导致`xmlHttp.responseText`在`readyState =2和3`的时候也正常输出了。不知道我的解释你是否明白。

另外我把你的源码改了一些（甚至包括方法名），也进行了重新分组，注释也重新整理了，还添加了一些方法，直接提交好像不太好。


这是我的一个库：[https://github.com/barnboo/pubsea/blob/master/js/pubSea.js](https://github.com/barnboo/pubsea/blob/master/js/pubSea.js)，其中的README.md里面有关于这个库（也就是你的库）的一些规划，是有打算联系你和你一起完善的想法的。
弄出来一个类似：[http://jquery.cuishifeng.cn/index.html](http://jquery.cuishifeng.cn/index.html)这个网站的，当然这是很好的设想了。

哈哈。

----------------------分割线--------------------------
链接是对的，不知道为什么打开就是404。- -！
复制出来居然可以打开。。。

**Comment by seayao** [comment]
比如你的getCount()方法，
我改为了arrGroupToArr()方法又增加了一个arrGroupToObj()方法(在SO社区比较有名的jsgroup)；
增加了getSameFromArray()获取两个数组相同的元素的方法；
增加了removeArrayOfIndex()删除数组中下标为n的元素的方法；
增加了与时间相关的7个方法包括你原来的getEndTime()方法；
等等。
还有一些自己写的美观的加载动画和闪烁、抖动（类似于提醒的功能）、滚动的插件等等没有添进去。

**Comment by chenhuiYj** [comment]
我看了一下，是不是贴错地址了？页面是404！不过我进入你的主页，也找到了这个仓库！
关于版权，我很高兴，因为您是一个很尊重版权的开发者！
关于提交，你那边进行了重新分组，注释也重新整理了，这个没事，到时候我这里合并就好，新开一个仓库。我也想大家一起维护一个！你从我这里fork一份，然后自己修改，提交，我这里就能收到新拉请求了，就可以合并了！
